apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nova-test
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>RHACM Demo</title></head>
    <body>
      <h1>🚀 RHACM + GitOps Demo</h1>
      <p>Bu uygulama ACM üzerinden GitOps ile deploy edildi!</p>
      <p>Cluster: ocp-qua-test</p>
    </body>
    </html>
