apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: nova-test
  labels:
    app: nginx-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx
          image: registry.access.redhat.com/ubi8/nginx-120:latest
          command: ["/bin/bash", "-c"]
          args:
            - nginx -g 'daemon off;'
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
